<?php
/**
 * Implements hook_wysiwyg_plugin().
 */
function ckeditor_responsive_tables_wysiwyg_plugin($editor, $version) {
    $plugins = array();
    if ($editor == 'ckeditor' && version_compare($version, '4.0', '>=')) {
        $plugins['responsive_tables'] = array(
            'path' => drupal_get_path('module', 'ckeditor_responsive_tables'),
            'buttons' => array(
                'Responsive Tables' => t('Responsive Tables'),
            ),
            'load' => TRUE,
            'internal' => FALSE,
        );
    }
    return $plugins;
}

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 */
function ckeditor_responsive_tables_wysiwyg_editor_settings_alter(&$settings, $context) {
    if ($context['profile']->editor == 'ckeditor') {
        $settings['allowedContent'] = TRUE;
        //Add in our CSS that applies *only* to the editor when it is open
        $settings['contentsCss'][] = "sites/all/modules/contrib/ckeditor_responsive_tables/css/rt_editor.css";
    }
}